<?php

namespace IPEXB2B;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-16 at 21:05:02.
 */
class ApiClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ApiClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ApiClient;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers IPEXB2B\ApiClient::setUp
     * @todo   Implement testSetUp().
     */
    public function testSetUp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::setupProperty
     * @todo   Implement testSetupProperty().
     */
    public function testSetupProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::curlInit
     * @todo   Implement testCurlInit().
     */
    public function testCurlInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::processInit
     * @todo   Implement testProcessInit().
     */
    public function testProcessInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::setSection
     * @todo   Implement testSetSection().
     */
    public function testSetSection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::getSection
     * @todo   Implement testGetSection().
     */
    public function testGetSection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::object2array
     * @todo   Implement testObject2array().
     */
    public function testObject2array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::objectToID
     * @todo   Implement testObjectToID().
     */
    public function testObjectToID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::setPostFields
     * @todo   Implement testSetPostFields().
     */
    public function testSetPostFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::getSectionURL
     * @todo   Implement testGetSectionURL().
     */
    public function testGetSectionURL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::sectionUrlWithSuffix
     * @todo   Implement testSectionUrlWithSuffix().
     */
    public function testSectionUrlWithSuffix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::addUrlParams
     */
    public function testAddUrlParams()
    {
        $this->assertEquals('http://vitexsoftware.cz/path?id=1&a=b',
            $this->object->addUrlParams('http://vitexsoftware.cz/path?a=b',
                ['id' => 1], TRUE));
    }

    /**
     * @covers IPEXB2B\ApiClient::updateApiURL
     * @todo   Implement testUpdateApiURL().
     */
    public function testUpdateApiURL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::requestData
     * @todo   Implement testRequestData().
     */
    public function testRequestData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::rawResponseToArray
     * @todo   Implement testRawResponseToArray().
     */
    public function testRawResponseToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::parseResponse
     * @todo   Implement testParseResponse().
     */
    public function testParseResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::parseError
     * @todo   Implement testParseError().
     */
    public function testParseError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::doCurlRequest
     * @todo   Implement testDoCurlRequest().
     */
    public function testDoCurlRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::xml2array
     * @todo   Implement testXml2array().
     */
    public function testXml2array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::loadFromIPEX
     * @todo   Implement testLoadFromIPEX().
     */
    public function testLoadFromIPEX()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::logResult
     * @todo   Implement testLogResult().
     */
    public function testLogResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::ipexDateTimeToDateTime
     * @todo   Implement testIpexDateTimeToDateTime().
     */
    public function testIpexDateTimeToDateTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::getTokenString
     * @todo   Implement testGetTokenString().
     */
    public function testGetTokenString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::ignore404
     * @todo   Implement testIgnore404().
     */
    public function testIgnore404()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::disconnect
     * @todo   Implement testDisconnect().
     */
    public function testDisconnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::__wakeup
     * @todo   Implement test__wakeup().
     */
    public function test__wakeup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IPEXB2B\ApiClient::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}