<?php

declare(strict_types=1);

/**
 * This file is part of the IpexB2B package
 *
 * https://github.com/Spoje-NET/ipex-b2b
 *
 * (c) Spoje.Net <https://spoje.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\IPEXB2B;

use IPEXB2B\Calls;
use PHPUnit\Framework\Attributes\CoversClass;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-06-15 at 11:34:23.
 */
#[CoversClass(Calls::class)]
class CallsTest extends ApiClientTest
{
    protected Calls $callsObject;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->callsObject = new Calls();
        $this->object = $this->callsObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \IPEXB2B\Calls::getCallsForNumber
     */
    public function testGetCallsForNumber(): void
    {
        $startDate = new \DateTime();
        $startDate->modify('-1 month');
        $calls = $this->callsObject->getCallsForNumber($startDate, (string) \Ease\Shared::cfg('TEST_TEL_NUM', '123456789'));
        $this->assertTrue(\is_array($calls) || \is_bool($calls));
    }

    /**
     * @covers \IPEXB2B\Calls::getCallsForCustomer
     */
    public function testLoadCallsForCustomer(): void
    {
        $startDate = new \DateTime();
        $startDate->modify('-1 month');
        $calls = $this->callsObject->getCallsForCustomer(
            $startDate,
            (int) \Ease\Shared::cfg('TEST_CUSTOMER_ID', 1),
        );
        $this->assertTrue(\is_array($calls) || \is_bool($calls));
    }
}
